### ISSUE TITLE
[fix]회원정보 입력 수정 오류 해결

### ISSUE THREAD

**Issue by seoin-cho** [SOLUX-2019/SantaIsSanta#60]
## 문제상황

- 회원가입, 회원정보 수정 페이지에서 minlength, maxlength 속성이 적용 안됨.
- 회원정보 수정 페이지에서 id는 수정 못하도록 제한해야 함.

## 진행상황

- [x] 회원 정보 입력, 수정 시 minlength, maxlength 속성 적용
- [x] 회원정보 수정 페이지에서 id는 수정 못하도록 설정
- [x] useNavigate() 사용

**Comment by mjms0214** [comment]
현재 디비 스키마 상에서는 이미지 type이 string으로 되어 있는 상태
